USE CDC_project;

#Delete rows in the head table
TRUNCATE TABLE cdc_2018_full;

LOAD DATA LOCAL INFILE '/private/tmp/CSV2018_full.csv'
INTO TABLE cdc_2018_full
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES ;

#Change date and facility columns to INT type
ALTER TABLE cdc_2018 
    MODIFY COLUMN DOB_YY INT, 
    MODIFY COLUMN DOB_MM INT,
    MODIFY COLUMN DOB_TT INT,
    MODIFY COLUMN DOB_WK INT,
    MODIFY COLUMN BFACIL INT,
    MODIFY COLUMN F_FACILITY INT,
    MODIFY COLUMN BFACIL3 INT;

#Change blank values for MAGE_IMPFLG and MAGE_REPFLG then convert to INT type
#takes 5 minutes to change blanks to NULL, need to extend connection timeout
UPDATE cdc_2018
	SET MAGE_IMPFLG = NULL 
	WHERE MAGE_IMPFLG = ' ';

ALTER TABLE cdc_2018 
    MODIFY COLUMN MAGE_IMPFLG INT;

UPDATE cdc_2018
	SET MAGE_REPFLG = NULL
	WHERE MAGE_REPFLG = ' ';

ALTER TABLE cdc_2018 
    MODIFY COLUMN MAGE_REPFLG INT;

#Change race columns to int
ALTER TABLE cdc_2018 
    MODIFY COLUMN MAGER INT, 
    MODIFY COLUMN MAGER14 INT,
    MODIFY COLUMN MAGER9 INT,
    MODIFY COLUMN RESTATUS INT,
    MODIFY COLUMN MBSTATE_REC INT,
    MODIFY COLUMN MRACE31 INT,
    MODIFY COLUMN MRACE6 INT,
    MODIFY COLUMN MRACE15 INT,
    MODIFY COLUMN MBRACE INT;
    
UPDATE cdc_2018
	SET MRACEIMP = NULL
	WHERE MRACEIMP = ' ';

ALTER TABLE cdc_2018 
    MODIFY COLUMN MRACEIMP INT;
    
    
    